import type { EclipseEntry } from "./eclipseCatalog";

/**
 * Loads the pre-built eclipse-to-countries mapping from
 * public/eclipse_countries.json (generated by scripts/build-eclipse-countries.mjs)
 * and populates entry.countries for each matching total eclipse.
 */
export async function loadCountryIndex(
  catalog: EclipseEntry[]
): Promise<void> {
  const resp = await fetch("/eclipse_countries.json");
  const index: Record<string, string[]> = await resp.json();

  for (const entry of catalog) {
    const countries = index[entry.label];
    if (countries) {
      entry.countries = countries;
    }
  }
}
